/* Generated by glib-genmarshal from libepc/marshal.list */
/* This file is generated, all changes will be lost */
#ifndef ___EPC_MARSHAL_MARSHAL_H__
#define ___EPC_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:ENUM,STRING,UINT (libepc/marshal.list:1) */
extern
void _epc_marshal_VOID__ENUM_STRING_UINT (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);

/* BOOLEAN:STRING (libepc/marshal.list:2) */
extern
void _epc_marshal_BOOLEAN__STRING (GClosure     *closure,
                                   GValue       *return_value,
                                   guint         n_param_values,
                                   const GValue *param_values,
                                   gpointer      invocation_hint,
                                   gpointer      marshal_data);

/* VOID:STRING,BOXED (libepc/marshal.list:3) */
extern
void _epc_marshal_VOID__STRING_BOXED (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* VOID:STRING,STRING (libepc/marshal.list:4) */
extern
void _epc_marshal_VOID__STRING_STRING (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);


G_END_DECLS

#endif /* ___EPC_MARSHAL_MARSHAL_H__ */
